// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package querier

import (
	"github.com/google/uuid"
)

type Application struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	Status    string
}
