// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package querier

import (
	"context"
)

type Querier interface {
	CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error)
	ListApplications(ctx context.Context, status string) ([]Application, error)
}

var _ Querier = (*Queries)(nil)
